# -*- coding: utf-8 -*-
"""SparkDataframe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xSzdcE4ye2Uw9gaGEoEo8TinBfC8Vkfn
"""

!pip install pyspark

from pyspark import SparkConf, SparkContext
from pyspark.sql import SparkSession
import collections
import pyspark

spark = SparkSession.builder.appName("Spark Dataframe").config("spark.some.config.option", "some-value").getOrCreate()

# spark is an existing SparkSession
df = spark.read.json("/content/people.json")
# Displays the content of the DataFrame to stdout
df.show()

df.collect()

# Select only the "name" column
df.select("name").show()